### ISSUE TITLE
Is it possible to use breakpoints with driver value maps?

### ISSUE THREAD

**Issue by bigsee** [alexfoxy/laxxx#131]
**Is your feature request related to a problem? Please describe.**
Since my layouts are different at different breakpoints and the scrollY values that trigger the animations should also be different. Lax allows me to change the animation values by breakpoint easily (awesome!). I don't know how I can easily do the same for driver values though.

**Describe the solution you'd like**
I'd like to be able to add different driver value maps for different breakpoints, to match the animation value maps (which can already be changed by breakpoint as [per the docs](https://github.com/alexfoxy/lax.js#value-maps)). e.g.:

``` js
lax.addElements('.selector, {
      scrollY: {
        opacity: [
          {
            375: ['elInY', 100, 520, 'elOutY'],
            600: ['elInY', 200, 'elOutY']
          },
          {
            375: [0, 1, 1, 0],
            600: [0, 1, 0]
          }
        ],
        translateX: [
          {
            375: ['elInY', 410, 520, 'elOutY'],
            600: [0, 215, 520, 'elOutY']
          },
          {
            375: [100, 0, 0, -200],
            600: [400, 0, 0, -200]
          }
        ]
      }
    })
```

**Describe alternatives you've considered**
Right now, my workaround is to include all of the driver values that will trigger animations and then try to map the correct animation values at various breakpoints. But this is time-consuming, repetitive and results in janky animations in some cases. Does anyone know of a better workaround?

**Comment by alexfoxy** [comment]
Hey. I suppose I imaged you'd be able to achieve this with the correct value maps for the screen sizes. I'll see how straight forward it will be to implement.

**Comment by bigsee** [comment]
@alexfoxy no worries at all. :) If it might avoid creating extra work, at a high level, how would you normally handle different value maps for each screen size? Detecting screen size on first load (and then again on resize event)? And, in this case, would I need to tear down and reinitialise lax with the new value maps (and do this for each driver)?

**Comment by alexfoxy** [comment]
Currently lax will re calculate the element value maps when the screen size changes:
```
      onWindowResize = () => {
        const changed = document.body.clientWidth !== this.windowWidth ||
          document.body.clientHeight !== this.windowHeight

        if (changed) {
          this.windowWidth = document.body.clientWidth
          this.windowHeight = document.body.clientHeight
          this.elements.forEach(el => el.calculateTransforms())
        }
      }
```
The same would need to be done for the drivers.

**Comment by alexfoxy** [comment]
From looking at the source code this already works! See https://codesandbox.io/s/breakpoints-with-driver-value-maps-dq4nr?file=/index.html

Hope that helps.
