### ISSUE TITLE
Single breakpoints are ignored in animation value maps

### ISSUE THREAD

**Issue by bigsee** [alexfoxy/laxxx#132]
**lax.js version**
v2.0.3

**Describe the bug**
When passing a breakpoint as an animation value map, this breakpoint is ignored. Reading the docs, I would expect the animations only to be applied at the single break point and below.

**Code**

This is the code I would like to use for animations that are only applied below a certain breakpoint:

``` js
lax.addElements('.selector', {
      scrollY: {
        opacity: [
          ['elInY', 410, 750, 'elOutY'],
          {
            375: [0, 1, 1, 0]
          }
        ],
        scale: [
          ['elInY', 410, 650, 'elOutY'],
          {
            375: [0, 1, 1, 0]
          }
        ],
        translateY: [
          ['elInY'],
          {
            375: [16]
          }
        ]
      }
    })
```

This is the workaround:

``` js
lax.addElements('.selector', {
      scrollY: {
        opacity: [
          ['elInY', 410, 750, 'elOutY'],
          {
            375: [0, 1, 1, 0],
            376: [1, 1, 1, 1]
          }
        ],
        scale: [
          ['elInY', 410, 650, 'elOutY'],
          {
            375: [0, 1, 1, 0],
            376: [1, 1, 1, 1]
          }
        ],
        translateY: [
          ['elInY'],
          {
            375: [16],
            376: [0]
          }
        ]
      }
    })
```

Is this expected behaviour? If so, I'd be happy to update this issue to the feature request template. 😄

**Comment by alexfoxy** [comment]
Heya - this isn't really intended behaviour but to be honest I didn't really imagine a case where animations would only be applied at some screen sizes but not others. On reflection it seems like an oversight. I'll look at fixing it at some point soon!

**Comment by alexfoxy** [comment]
Just had a look at fixing this issue, the difficulty is that you'll probably need to define some sort of default value. I can see in your example sometimes that's 0 and sometimes that's 1. Although perhaps not pretty, your solution _does_ work and I'm not sure it's worth adding the complexity to the code base when it won't really provide a better solution.
