### ISSUE TITLE
Mobile not work

### ISSUE THREAD

**Issue by fabiosilvanet** [alexfoxy/laxxx#133]
Hi,

I'm trying use this explorer to get presets: https://alexfox.dev/lax.js/preset-explorer

I use this on my website, but on my mobile phone it's not working. Only on desktop. :-( Maybe I made something wrong?

For example: class ="lax lax_preset_spin:824:360"

Thank you very much.

**Comment by alexfoxy** [comment]
Heya,

The present explorer works on my phone ok. What device are you using?
