### ISSUE TITLE
elOutY does not play well with position: sticky

### ISSUE THREAD

**Issue by Burtonium** [alexfoxy/laxxx#134]
**lax.js version**
Lax.js v2.0.3

**Describe the bug**
elOutY and elInY presume that an element will scroll normally to the top by calculating the screenHeight from the point it loads. This is, of course, erroneous when using `position: sticky`.

**Code**
https://codesandbox.io/s/long-architecture-6kw60?file=/src/index.js

**Comment by alexfoxy** [comment]
Interesting, not sure it's a bug per-say, more a limitation of how lax works. We can't calculate the distance from top every frame as it would cause poor performance.

For now I recommend using `index` and some calculation with screenHeight to get your desired effect.
