### ISSUE TITLE
Support for non-CSS values

### ISSUE THREAD

**Issue by leifniem** [alexfoxy/laxxx#135]
**Is your feature request related to a problem? Please describe.**
I recently found myself wishing lax would support animating values of JS objects (specifically three.js position)

**Describe the solution you'd like**
The ability to map output of a lax element to a custom output

**Describe alternatives you've considered**
Currently i use a very barebones scroll event listener that has no regard for intersections or the like

**Comment by alexfoxy** [comment]
@leifniem I wonder if you could use onUpdate to update three.js position: https://github.com/alexfoxy/lax.js#onupdate-drivervalues-object-domelement-domelement--void

For example:
```
lax.addDriver('scrollY', function () {
    return window.scrollY
})

lax.addElements("#text", {}, {
    onUpdate: function (driverValues, domElement) {
        const scrollY = driverValues.scrollY[0]
        myThreeJsValue = scrollY 
    }
})

```

Would that work?

**Comment by leifniem** [comment]
@alexfoxy absolutely, thank you! And my apologies for not checking the docs enough. 😅
