### ISSUE TITLE
How to use presets; what do the values mean?

### ISSUE THREAD

**Issue by jipasveld** [alexfoxy/laxxx#137]
Hello.

I would like to use the plugin (I used version 1.0 before and this one seems to much more powerful!) but it is for an experimental website, with many (only) moving images.. So to keep things clear for myself, I want to use the presets. However, I do not really understand what the values mean (underlined and in bold below)

<div class="lax lax_preset_fadeIn:**_50_**:**_100_** lax_preset_spin"></div>

I played around with changing them, but I do not really understand the logics yet. Would be nice if you could explain this a bit more.

Thank! -Jip

**Comment by alexfoxy** [comment]
Hey! Not sure if you posted your full message as I can’t see the code you referred to.

**Comment by jipasveld** [comment]
Well, for now it's not related to specific code but more in general, what the numbers refer to for the preset code. So for instance, this code which is the general example on the instructions page (for some reason, it wasn't published in my previous post..):

`<div class="lax lax_preset_fadeIn:50:100 lax_preset_spin"></div>`

The numbers aren't explained there and I cannot really figure them out.
Thanks already for the help!

**Comment by jipasveld** [comment]
Okay, my code didnt appear again, but I editted it and now it displays (I am new to github).

To give some more context to my question (I have been trying to make it work, without success, but at least I have a specific effect I want to create now): I have an image in the middle of the screen (when it loads) which after scrolling, needs to get bigger (scale) and move to the right (slideX), so that it appears to move besides the viewer (in a perspective view). For that, I have the following line, but whatever I do with the numbers, I cannot make it work in the way I want. Can you explain how I can set this up?

`<img src="./images/example.png" class="lax lax_preset_slideX:1242:1000 lax_preset_scaleIn:414:2">  `

Thanks, Jip

**Comment by rickvian** [comment]
hi @jipasveld i don't  think this is an issue hence github issue page is not right place to ask for tutorial (CMIIW)
you can play around with the preset settings to have better idea on how it works
here : https://alexfox.dev/lax.js/preset-explorer
