### ISSUE TITLE
About the use of presets in React

### ISSUE THREAD

**Issue by Devilson8** [alexfoxy/laxxx#138]
I could notice in React, that there is the 
addElements in order to use the elements from lax 

But now I wonder if there is any way of using the presets in react
by using addPreset, in a very simple way possible??

**Comment by Devilson8** [comment]
<p class="desc" data-lax-preset="blurInOut fadeInOut">
                Love, dedication.
   </p>

Not working in react

**Comment by alexfoxy** [comment]
Sorry addPreset is not supported in Lax.js 2.0
