### ISSUE TITLE
Cannot read property 'presets' of undefined

### ISSUE THREAD

**Issue by kingbiscit** [alexfoxy/laxxx#139]
Using import lax from 'lax.js';

I get the error

Cannot read property 'presets' of undefined

**Comment by alexfoxy** [comment]
Are you using Lax v1 or v2?

**Comment by jaunt** [comment]
I just installed the latest and greatest and see the same issue (v2)
```
Uncaught TypeError: Cannot read property 'presets' of undefined
    at eval (lax.min.js:1)
    at Array.forEach (<anonymous>)
    at eval (lax.min.js:1)
    at f.eval [as calculateTransforms] (lax.min.js:1)
    at new f (lax.min.js:1)
    at eval (lax.min.js:1)
    at NodeList.forEach (<anonymous>)
    at eval [as findAndAddElements] (lax.min.js:1)
    at eval [as init] (lax.min.js:1)
    at window.onload (main.js:15)

**Comment by jaunt** [comment]
I found a hack-workaround for now.  Seemingly safe since I don't see any other references to windows.lax from lax.min.js?

```
import lax from 'lax.js'

window.onload = function () {
  window.lax = { presets: lax.presets }

  lax.init()

  // Add a driver that we use to control our animations
  lax.addDriver('scrollY', function () {
    return window.scrollY
  })
}

**Comment by alexfoxy** [comment]
Can you share your full code?

**Comment by jaunt** [comment]
I will try to put something together as soon as I get a chance -- using in the context of an eleventy project using webpack.

**Comment by alexfoxy** [comment]
Closed due to inactivity.

**Comment by loranger** [comment]
I had the same issue and tried @jaunt ' workaround (`window.lax = { presets: lax.presets }`) which works perfectly.

I try to use lax within a laravel project which compile js using [laravel-mix](https://laravel-mix.com/) webpack wrapper.

If you still want a full code, @alexfoxy, here it is, but I'm afraid there isn't anything more:

<details>
<summary>
<code>app.js</code>
</summary>

```javascript
import lax from 'lax.js'

window.onload = function() {
    window.lax = { presets: lax.presets }
    lax.init()

    lax.addDriver('scrollY', function() {
        return window.scrollY
    })
}

```

</details>


<details>
<summary>
<code>homepage.blade.php</code>
</summary>

```php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>{{ config('app.name') }}</title>
    <link rel="stylesheet" href="{{ mix('css/app.css') }}" media="all">
  </head>
  <body>

    <div class="container">
        <h1 data-mask="{{ strtolower(config('app.name')) }}" class="fill lax lax_preset_fadeIn:50:100 lax_preset_spin">
            {{ strtolower(config('app.name')) }}
        </h1>
    </div>

    <script src="{{ mix('js/app.js') }}"></script>

  </body>
</html>

```

</details>


<details>
<summary>
<code>rendered homepage</code>
</summary>

```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Demo</title>
    <link rel="stylesheet" href="/css/app.css?id=22513219556a7675a729" media="all">
  </head>
  <body>

    <div class="container">
        <h1 data-mask="demo" class="fill lax lax_preset_fadeIn:50:100 lax_preset_spin">
            Demo
        </h1>

    </div>

    <script src="/js/app.js?id=234c3be3ea51ff9c1c7b"></script>

  </body>
</html>

```

</details>

**Comment by alexfoxy** [comment]
> I had the same issue and tried @jaunt ' workaround (`window.lax = { presets: lax.presets }`) which works perfectly.
> 
> I try to use lax within a laravel project which compile js using [laravel-mix](https://laravel-mix.com/) webpack wrapper.
> 
> If you still want a full code, @alexfoxy, here it is, but I'm afraid there isn't anything more:
> 
> `app.js`
> ```js
> import lax from 'lax.js'
> 
> window.onload = function() {
>     window.lax = { presets: lax.presets }
>     lax.init()
> 
>     lax.addDriver('scrollY', function() {
>         return window.scrollY
>     })
> }
> ```
> 
> `homepage.blade.php`
> `rendered homepage`

We could just add the "hack" into the docs for any users who want to do this?

**Comment by djmtype** [comment]
Just wanted to note using with Vite with a vanillajs project and got the same error. Resolved with the hack above.

**Comment by derwaldgeist** [comment]
Same for React. `window.lax = { presets: lax.presets }` does the trick, but that's not really a nice solution, as it pollutes the global namespace.

**Comment by VandeVoordeMatthias** [comment]
Tried it today with Vite, the issue stills exists. The hack fixed it.
