### ISSUE TITLE
Trigger preset when in viewport

### ISSUE THREAD

**Issue by PubliAlex** [alexfoxy/laxxx#140]
Hello,

I don't see in the documentation how to start triggering a preset when it enter on the viewport. It was so easy with the V1.

I try to make a title going from right to left when it enter the viewport.

I have this : 

`<h2 class="bigtitle lax lax_preset_slideX:?????:-1920">L'actualité de publipresse</h2>`

Don't know what to put to replace the ????? to trigger my preset when it enter the viewport.

Another side question, but I need to make my text completely traverse the screen from right to left, instead of putting 1920 as raw PX value, which can work only on FULL HD screen, I would like to put "100vw" which correspond to the width of my screen (better for responsive)

Thank you for your help

**Comment by alexfoxy** [comment]
I would suggest using a custom animation as the presets are somewhat limited.
https://github.com/alexfoxy/lax.js#custom-animations
