### ISSUE TITLE
Presets seem to behave in inverted way

### ISSUE THREAD

**Issue by ls15web** [alexfoxy/laxxx#141]
When I try to get presets, such as scaleIn working, they seem to behave in an inverted way: Instead of scaling from 0% to 100%, the element scales from 100% to 0%, while it enters the viewport.

See following fiddle with the current CDN version (https://cdn.jsdelivr.net/npm/lax.js):
https://jsfiddle.net/bhosfL8k/

Am I doing it wrong, or is this a bug?

**Comment by rickvian** [comment]
I just tested with the [preset explorer ](https://alexfox.dev/lax.js/preset-explorer) and somehow
under 100 distance it behaves inverted until certain distance (yes i think its bug)

![Image 396](https://user-images.githubusercontent.com/8034141/116820778-e2049400-aba0-11eb-934e-6dd840567217.png)

meanwhile, have you try to use lax.addElements instead?

**Comment by alexfoxy** [comment]
> When I try to get presets, such as scaleIn working, they seem to behave in an inverted way: Instead of scaling from 0% to 100%, the element scales from 100% to 0%, while it enters the viewport.
> 
> See following fiddle with the current CDN version (https://cdn.jsdelivr.net/npm/lax.js):
> https://jsfiddle.net/bhosfL8k/
> 
> Am I doing it wrong, or is this a bug?

I think you need to set the value to greater than 0. Try this `<div class="box box-blue lax lax_preset_scaleIn:200:0">` instead

**Comment by bfintal** [comment]
I think this needs to be reopened. It's still inverted: https://jsfiddle.net/25krwufd/2/
