### ISSUE TITLE
Question: code for demo project

### ISSUE THREAD

**Issue by MizuBishi** [alexfoxy/laxxx#142]
Hi there, 

Thank you so much for your work, it is awesome. 
Is the code for the [demo](https://alexfox.dev/lax.js/) somewhere available? I would like to have a text scaled on scrolling (similar to the "x" in the demo). Thank you so much!

**Comment by MarkusHeinisch** [comment]
You can easily show the source code from the demo page and copy/paste the code snippet:
view-source:https://alexfox.dev/lax.js/

**Comment by arthurdenner** [comment]
It's also available here on GitHub: https://github.com/alexfoxy/lax.js/blob/dev/docs/index.html

**Comment by MizuBishi** [comment]
Thank you guys!!!!
