### ISSUE TITLE
Vue 3 Example

### ISSUE THREAD

**Issue by CKGrafico** [alexfoxy/laxxx#144]
I was trying to find a Vue 3 example but was impossiible to em to find one, I've made my own simple example

https://github.com/alexfoxy/lax.js/issues

**Comment by alexfoxy** [comment]
If you'd like to add your Vue 3 example to the github send it over and I can add it to the readme.

**Comment by MarcHajjar0** [comment]
Hello,

I can't seem to find the example. I've been struggling to make it work with Vue3, can you please lead me to a start
