### ISSUE TITLE
Upgrade dependency to React 17.x

### ISSUE THREAD

**Issue by MarkusHeinisch** [alexfoxy/laxxx#145]

**Comment by arthurdenner** [comment]
In case this issue is about the [`use-lax`](https://github.com/arthurdenner/use-lax) library, support for React 17.x was added in `4.0.3` in https://github.com/arthurdenner/use-lax/commit/86138cdefe6816029e2a930157b665da4ffef0fc.

**Comment by MarkusHeinisch** [comment]
Thanks sir.
