### ISSUE TITLE
Responsive breakpoints doesn't work on change window size 

### ISSUE THREAD

**Issue by MarkusHeinisch** [alexfoxy/laxxx#147]
I've added these two maps, but if i use the chrome dev tool with responsive mode or i simply change the window size, the breakpoints doesn't work. It only works when i switch manually to pixel 2 or desktop resolution. 

`{
				selector: '.foo1-1',
				animationData: {
					scrollY: {
						translateX: [
							['elInY', 'elCenterY+200', 'elOutY'],
							{
								1023: [0, 0, 0],
								1024: [0, 0, '-screenWidth'],
							},
						],
					},
				},
			},`

**Comment by alexfoxy** [comment]
Please provide some example code or a codepen for me to look at.

**Comment by MarkusHeinisch** [comment]
Its solved
