### ISSUE TITLE
Optimisations and changes to demo (index.html)

### ISSUE THREAD

**Issue by co16353sidak** [alexfoxy/laxxx#15]
Love this new resource and would love to try and contribute as much as possible.

I feel that the `index.html` file inside the docs folder could be a little optimised by separating the `js` and `css` and also I have noticed the page lacks a `title` which could be displayed (something catchy or descriptive yet short).
also we could add some `fork on GitHub` or `star go Github` buttons to increase some reach and make it easy for people to access the repo from the website.

Would love to work on these as well, so please let me know what you think. 🥇 
/cc: @alexfoxy

**Comment by alexfoxy** [comment]
Yea, I'll look at adding these in.
