### ISSUE TITLE
Can I add DOM from jQuery

### ISSUE THREAD

**Issue by katsar0v** [alexfoxy/laxxx#158]
**Is your feature request related to a problem? Please describe.**
It would be great if I could add a dom with jQuery, e.g. `$('.selector')[0]` as a first parameter for `lax.addElements`

**Comment by PatrickDesign** [comment]
Seems like a good idea to me. Here's a PR if you agree @alexfoxy: https://github.com/alexfoxy/lax.js/pull/159#issue-1020369179,  🙇

**Comment by alexfoxy** [comment]
Fixed on dev branch, will be in an up coming release with typescript support.
