### ISSUE TITLE
Changing color on scroll

### ISSUE THREAD

**Issue by loranger** [alexfoxy/laxxx#161]
**lax.js 2.0.3**

**Describe the bug**
I'd like to create a background color changing effect on scroll, but can't figure out where to start. Do you have any clue for me please ? Do I have to write a custom css function callback in order to compute the correct color depending on the scroll possition ?

**Code**
```javascript
    lax.addElements(
      'body',
      {
        scrollY: {
          "background-color": [
            [0, 100],
            ['#FFFFFF', '#000000'],
          ]
        }
      }
    );
```

**Comment by alexfoxy** [comment]
Only specific CSS properties are possible, see https://github.com/alexfoxy/lax.js#css-properties

I suggest trying : `hue-rotate` or `brightness`
