### ISSUE TITLE
Support / Example for Svelte

### ISSUE THREAD

**Issue by PezzerDev** [alexfoxy/laxxx#168]
lax.js doesn't seem to play well with Svelte/SvelteKit. From my crude observations, it appears that the driver function isn't being executed to progress the animation (a single execution occurs on load, and then nothing beyond).

I'm sure there's a way to work around Svelte's compilation/execution model. It would be great to see an example of how this could work.

**Comment by akuales** [comment]
Did you ever find a solution for it?
