### ISSUE TITLE
Trigger video playback

### ISSUE THREAD

**Issue by derwaldgeist** [alexfoxy/laxxx#171]
We have a video that should start playback once a certain scroll position has been reached. Is this possible with lax?

**Comment by arthurdenner** [comment]
`lax.js` is meant to drive animations from scroll, without side-effects. I'd suggest using an `IntersectionObserver` to your case: https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API

**Comment by derwaldgeist** [comment]
Thanks, I will try that out!

**Comment by derwaldgeist** [comment]
I was able to implement it with IntersectionObserver, all good! Thanks.
