### ISSUE TITLE
Support for backgroundPositionX and backgroundPositionY

### ISSUE THREAD

**Issue by derwaldgeist** [alexfoxy/laxxx#175]
For parallax effects, it would be great if the background position of a div could be animated as well. At the moment, this is not possible.

**Comment by alexfoxy** [comment]
This is possible with a custom cssFn. See the code of one of the examples:

https://github.com/alexfoxy/lax.js/blob/dev/docs/examples/sprite.html

**Comment by derwaldgeist** [comment]
Thanks!
