### ISSUE TITLE
Drift functions

### ISSUE THREAD

**Issue by afanjul** [alexfoxy/laxxx#18]
Another question regarding drift functions (I didn't check anymore) is that, typically (as web designer) you position an element in the **"right position"** without thinking in animations or so. After that, you plan to drop-in an animation library so the elements "appear animated" but you expect (I think) that the final position of the element stay in the **"right position"** you defined before, otherwise your element ends at 100px or 50px offset of the "right position". 

So in my opinion (_but maybe I'm wrong_), functions like driftLeft (I didn't review anymore) should be like this:

`driftLeft: (v=100) => {
        return { "data-lax-translate-x": 'vh ${v}, elh 0' }
      },
      driftRight: (v=100) => {
        return { "data-lax-translate-x": 'vh ${-v}, elh 0' }
      },` 

So the element start "offsetted" and ends in the "right position" you originally had it. I don't know what is the consensus among other animation libraries... but I like to think that if for any reason the user lacks of javasript, the elements place the right position.

**Comment by alexfoxy** [comment]
Not sure about this. Personally I think it should start in the right place and move across. You can define custom transitions if you want more control.
