### ISSUE TITLE
NPM

### ISSUE THREAD

**Issue by antonreshetov** [alexfoxy/laxxx#2]
Do you have plans to publish to NPM?

**Comment by alexfoxy** [comment]
Yes, I’ll have a look.

**Comment by alexfoxy** [comment]
@antonreshetov published over at: https://www.npmjs.com/package/lax.js

Let me know if it works ok 👍

**Comment by antonreshetov** [comment]
@alexfoxy Cool, but not correct path to main script. I made PR #3 for fix it

**Comment by alexfoxy** [comment]
@antonreshetov good catch, merged and published 1.0.3
