### ISSUE TITLE
 Scroll-linked effects warning

### ISSUE THREAD

**Issue by bedax** [alexfoxy/laxxx#26]
This looks like a really excellent library. I have been avoiding these sort of techniques due to the following warning that firefox gives:

`This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!`

It would be nice if you acknowledged this warning in the readme, saying briefly how you overcome this problem so it's clear that this isn't going to break in a few browser versions.

**Comment by alexfoxy** [comment]
I have changed the functionality to use requestAnimationFrame in the latest 1.2.0 version so this shouldn't be an issue any more.
