### ISSUE TITLE
Horizontal / Direction option

### ISSUE THREAD

**Issue by jq-87** [alexfoxy/laxxx#28]
Cool plugin - any plans to add a horizontal / direction option?

**Comment by alexfoxy** [comment]
You could pass in the scrollX into the update function e.g `lax.update(window.scrollX)` - I can't imagine wanting both scrollX & scrollY ?

**Comment by alexfoxy** [comment]
@jq-87 does this work for you?

**Comment by emreisik95** [comment]
> @jq-87 does this work for you?

Hey there, this doesn't work for me. Is there any other options?

**Comment by alexfoxy** [comment]
@emreisik95 can you elaborate? Do you have a code example?
