### ISSUE TITLE
Scrool Y for x pixels / 150vw then revert to normal scroll

### ISSUE THREAD

**Issue by sagive** [alexfoxy/laxxx#33]
Hey, I love this project!
i am just missing some functionality (or don't know how to apply it)

I do a lot of projects where I scroll an element on its Y axis until a certain point and then move on to scroll the page on the X-axis.

Or for example, PIN a section for an x amount of "length" and then continue to scroll normally...

For example (a recent project)
a mix between scrollMagic & Slick Slider...
https://www.scadafence.com/platform-technology/

Any way to achieve this or [that](https://www.scadafence.com/) using laxxx?

**Comment by alexfoxy** [comment]
It is possible. I made a very simple example here: https://codepen.io/alexfoxy/pen/yrLGog

Hope that explains it enough!

**Comment by sagive** [comment]
This awesome alex, Thanks for quick response and the example ;)

Can u explain the values inside the translate-x? 
_(or share a link < i value your time - just want to understand)_
data-lax-translate-x="0 0, 500 -1000"

**Comment by sagive** [comment]
Thanks a lot alex, 
i really appreciate your help and all the time you put into the project  ;)

**Comment by alexfoxy** [comment]
@sagive you're welcome !
