### ISSUE TITLE
lax.populateElements() function doesn't work properly..

### ISSUE THREAD

**Issue by lisongting95** [alexfoxy/laxxx#34]
window.addEventListener("resize", function() {
	lax.populateElements()
});

when i use this , my image size was ruined..i don't know what happened. .

**Comment by alexfoxy** [comment]
Do you have a link to an example ?

**Comment by nicofonseca** [comment]
Your site has the same problem.
[https://alexfox.dev/laxxx/](https://alexfox.dev/laxxx/)

If you resize the browser the parallax breaks.

<img width="1276" alt="Screen Shot 2019-04-02 at 18 54 45" src="https://user-images.githubusercontent.com/12025749/55438720-cde0a980-5578-11e9-9632-e09fc470405b.png">

**Comment by nicofonseca** [comment]
Here is the problem, you are not overwriting the transform properties.
![Screen Shot 2019-04-02 at 18 58 19](https://user-images.githubusercontent.com/12025749/55438931-6840ed00-5579-11e9-9366-a20d87ab7e9b.png)

**Comment by alexfoxy** [comment]
Hey - I have fixed in v1.2.1 👍
