### ISSUE TITLE
Missing lax.addElement(domElement)

### ISSUE THREAD

**Issue by Cryptonex7** [alexfoxy/laxxx#36]
The lax.js file has no function names addElement().

`TypeError: lax_js__WEBPACK_IMPORTED_MODULE_9___default.a.addElement is not a function`

I am using a create-react-app React Project and have done an npm install.
![image](https://user-images.githubusercontent.com/34197902/55497103-348bc300-565e-11e9-9f7f-35e9f1c0007b.png)

**Comment by alexfoxy** [comment]
Thanks for pointing it out - fixed in 1.2.2
