### ISSUE TITLE
lax.populateElements(), still broken

### ISSUE THREAD

**Issue by joesawa** [alexfoxy/laxxx#37]
Hey brother, loving this tool so far. I'm still having the same issue with `lax.populateElements()` as #34, despite upgrading to 1.2.2 (which I see you published very recently)

![Screen Shot 2019-04-03 at 1 54 42 PM](https://user-images.githubusercontent.com/34663278/55501363-40ed2d00-5618-11e9-89e2-588969128689.png)

Translate rules are not being overwritten on page resize, as you can see here.

**Comment by alexfoxy** [comment]
Can you share your code? I just fixed my example to use the latest version: https://alexfox.dev/laxxx/

**Comment by joesawa** [comment]
Pretty straightforward. I fire it on page load, using code from your examples.

```
	window.onload = function() {
		lax.setup() // init

		const updateLax = () => {
			lax.update(window.scrollY)
			window.requestAnimationFrame(updateLax)
		}

		window.requestAnimationFrame(updateLax)
	}

	window.addEventListener("resize", function() {
		lax.populateElements()
	});
```

**Comment by alexfoxy** [comment]
Sorry, It's because I didn't update the read me - I will do it now. You need to do:

```
window.addEventListener("resize", function() {
	lax.updateElements()
});
```

Working pen : https://codepen.io/alexfoxy/pen/ROrroZ

**Comment by joesawa** [comment]
Thank you :)
