### ISSUE TITLE
Is this supposed to work on iOS?

### ISSUE THREAD

**Issue by p3lican** [alexfoxy/laxxx#38]
Just wondering if anyone has got this to work on iOS?

I've tested with Safari and Chrome and don't get the scroll effect. Just making sure I'm not doing something wrong here. I am using the smoothscroll plugin in addition.

Thanks for any info on this!

**Comment by alexfoxy** [comment]
Yes - have you tried the demo on your phone => https://alexfox.dev/laxxx/ ?

**Comment by p3lican** [comment]
Thanks Alex.
It's possible codepen could be causing an issue previewing. I'm glad to know this works on iOS. I checked your example and it definitely works smoothly. I'm going to host it off-codepen and see if I have better luck.

Great plugin by the way!

**Comment by p3lican** [comment]
And of course, it is codepen's Live preview that was causing the effect to not work!

Works perfectly hosted off codepen.

The love/hate with CP continues....

Again, great plugin!

**Comment by alexfoxy** [comment]
Haha - yeah I know what you mean about CP ;)
