### ISSUE TITLE
Smooth scroll application - open source, better alternative

### ISSUE THREAD

**Issue by robertpiosik** [alexfoxy/laxxx#39]
👋hi 

The laxxx documentation mentions an app to smooth scroll out. 

> Scroll Wheels
> Scroll wheels only increment the scroll position in steps which can cause the animations to look janky. You can use the SmoothScroll (http://www.smoothscroll.net/) plugin to smooth this out, however there maybe performance implications that need investigating.

[https://github.com/alexfoxy/laxxx#scroll-wheels](https://github.com/alexfoxy/laxxx#scroll-wheels)

This application is good but paid and linking to much better open sourced alternative is worth your consideration ☺️

[https://github.com/Caldis/Mos](https://github.com/Caldis/Mos)

Good work on the lib 👏Keep it going!;)

**Comment by alexfoxy** [comment]
This just seems like a Mac application, not sure it's right for the project.

**Comment by robertpiosik** [comment]
SmoothScroll is also a Mac app, also not sure if mentioning any sort of is right there.

**Comment by alexfoxy** [comment]
Hm, somehow linked to the wrong thing.. I'll fix it on Monday.
