### ISSUE TITLE
Stop after initial scroll

### ISSUE THREAD

**Issue by snorkelbork** [alexfoxy/laxxx#42]
Hi,

Brilliant lib, just wondering if it would be possible at all for the animations to stop after a first initial scroll? I have put a window.onscroll that adds elements to do this currently but it's a bit hacky really.

Was wondering if there was intent to a single scroll function?

**Comment by alexfoxy** [comment]
Hey - glad you like it!

I guess the easiest way is to use the animation loop: 
```
	const thresh = 100
        let scrolledOverThresh = false
        const updateLax = () => {
                if(!scrolledOverThresh) {
                       lax.update(window.scrollY)
                       if(window.scrollY > thresh) scrolledOverThresh  = true
                 }
		window.requestAnimationFrame(updateLax)
	}

	window.requestAnimationFrame(updateLax)
```

**Comment by snorkelbork** [comment]
Hey, it didn't seem to work as intended but it could have to do with something with my set up (using twig wp etc) as it sits within a loop.

I'm going to do some testing in codepen and i'll let you know, nice one for the quick response also.

**Comment by alexfoxy** [comment]
Ah, I didn't test, was just the gist. Send over the codepen if you like.

**Comment by snorkelbork** [comment]
No worries, i've managed to fix it by tweaking your snippet slightly and messing with some of the mark up. Again, thanks for quick responses!
