### ISSUE TITLE
How use presets in React with hooks?

### ISSUE THREAD

**Issue by rteobaldo** [alexfoxy/laxxx#44]
There is some way to do that?

**Comment by alexfoxy** [comment]
There's an example in the use-lax repo : https://github.com/arthurdenner/use-lax

**Comment by arctouch-rodrigoteobaldo** [comment]
Sorry, let me ask in a better way. There is a way to create a custom presets with hooks?

Like this one: 
```
lax.addPreset("myCoolPreset", function() {
	return { 
		"data-lax-opacity": "(-vh*0.8) 40, (-vh*0.6) 0",
		"data-lax-rotate": "(-vh*2) 1000, (-vh*0.5) 0" 
	}
})
```

**Comment by rteobaldo** [comment]
Sorry, let me ask in a better way. There is a way to create a custom presets with hooks?

Like this one:
```
lax.addPreset("myCoolPreset", function() {
	return { 
		"data-lax-opacity": "(-vh*0.8) 40, (-vh*0.6) 0",
		"data-lax-rotate": "(-vh*2) 1000, (-vh*0.5) 0" 
	}
})
```

**Comment by alexfoxy** [comment]
Perhaps you can do something like
```
import lax from 'lax.js';
lax.addPreset(...)
```

In your main app. I'd ask the guy who wrote the use-lax as he might know more about the implementation.

**Comment by Devilson8** [comment]
Good day,
Did you guys found the solution?

**Comment by arthurdenner** [comment]
Hi! 👋🏽 

Author of [`use-lax`](https://github.com/arthurdenner/use-lax) here.

AFAIK, there's no API for adding presets in lax.js v2. If you're using v1, I think you can call `lax.addPreset` after calling `lax.setup`.
