### ISSUE TITLE
Add anchored element width and height as new special values

### ISSUE THREAD

**Issue by rteobaldo** [alexfoxy/laxxx#45]
When I need to use width/height of some anchored element I need to use this method: 
```
...
data-lax-opacity="(vh) 0, 0 1, (-document.querySelector('.status').clientHeight+100) 1, (-document.querySelector('.status').clientHeight) 0"
data-lax-anchor=".status"
...
```

I don't know if exists another way to do this, but I think would be great to have special values as `aelw` and `aelh` to help on that.

**Comment by alexfoxy** [comment]
Does `elh` not do the job?

**Comment by rteobaldo** [comment]
In this example: https://codesandbox.io/embed/8kymplvqkj

Let's think that I need to translate vertically the `h1` when it start to touch the second section. But I need to translate this in the same value of the anchored element height. In this case I'm using elh but this returns just the height of `h1`, the target element. I need the anchored element size. Because with this I can work with relative sizes.

Btw relative units don't work as expected, like `100%`. It becames `100px` instead.

Let me know if I wasn't clear.

**Comment by mikestempien** [comment]
+1

**Comment by torsteinringnes** [comment]
+1

**Comment by torsteinringnes** [comment]
@rteobaldo 
At line 261 you could add:
```
.replace(/ah/g, o["data-lax-anchor"].clientHeight)
.replace(/aw/g, o["data-lax-anchor"].clientWidth)
```
Now you can use special values ah(anchor-element-height) and aw(anchor-element-width) - this depends on setting `data-lax-anchor` as the first attribute.
I use this in my projects and it works fine, but cant create a PR for some reason :(
