### ISSUE TITLE
Support for other CSS properties

### ISSUE THREAD

**Issue by danielhaan** [alexfoxy/laxxx#46]
Hello,

Are there any plans for adding support to other properties, such as `width`, `height`, `top`, `left`, `padding`, `margin`, etc...

Just curious, as if not, I'll look at another way to handle animating them on scroll :)

**Comment by alexfoxy** [comment]
The issue is performance - every time you set those properties it causes a reflow of the layout. You can use translate instead of top/left and scale for width/height. Not quite the same but might be enough.

Do you have an example of what you'd like to do?

**Comment by danielhaan** [comment]
Okay, that makes sense :) I'm trying to make a bar graph expand as you scroll down. In my context, the bar graph elements are not affecting the layout, since they are placed inside a container with a fixed height, but perhaps the browser will still identify a height change regardless?

I could pursue solving it with scale, as that might give me the solution I'm looking for. Right now I just made a "trigger" at a certain height, where the element heights are added with javascript and then a css transition makes them look animated.
