### ISSUE TITLE
Animate elements outside the component which is scrolled.

### ISSUE THREAD

**Issue by Xenos5282** [alexfoxy/laxxx#50]
I am not able to animate those elements which are outside the element which is been scrolled.
I have three parallel vertical divs. One div has element which can be scrolled and I want to animate an SVG which is in the other div which cant be scrolled, and not able to do so currently.

**Comment by alexfoxy** [comment]
Can you post your example online somewhere?

**Comment by stagedataloss3** [comment]
test123test123HelloWorld
