### ISSUE TITLE
Lazy moves element down

### ISSUE THREAD

**Issue by paulzz3000** [alexfoxy/laxxx#51]
When adding, for example, data-lax-preset="lazy-250" the element is shifted down the viewport by an amount relative to the strength. Is this expected behaviour?

**Comment by alexfoxy** [comment]
The idea was that the element would move up the page more slowly than you were scrolling, it's tricky to get it right with a preset. If you have a suggestion for a better preset please add a PR :)

**Comment by paulzz3000** [comment]
Thanks Alex, sure, slower than other bits but why does it move the element down before scroll? It shifts the element several hundred pixels down. What can I do to correct this and move element back to its original start position (before lax applied).
