### ISSUE TITLE
Anchor has no effect on presets

### ISSUE THREAD

**Issue by nicklassandell** [alexfoxy/laxxx#52]
The documentation states that "self" is the default anchor for presets, but I am unable to override it. Using a preset (built in or custom) I am unable to manually set an anchor with the data-lax-anchor attribute. It will use "self" regardless of what is supplied. This seems to be a bug?

**Comment by alexfoxy** [comment]
Hey! I just pushed a fix on the dev branch. Can you check if it fixes your problem? :)

**Comment by willryanuk** [comment]
This patch worked for me, would be great to get it into master. I was stuck with this for a while! Thanks for the work on this library, really useful stuff.

**Comment by alexfoxy** [comment]
Merged !
