### ISSUE TITLE
Manage animations with javascript

### ISSUE THREAD

**Issue by PubliAlex** [alexfoxy/laxxx#54]
Hello,

I have a website that have the same element many many time. That element always have the same class.

Instead of copying html attributes to all that elements with the preset I want to apply, I would like to be able to do it using javascript.

Your documentation don't mention that possibility, is it possible, and if yes, do you have a small code example ?

Thank you, and congratulation for this excellent plugin !

**Comment by alexfoxy** [comment]
Hey,

Could you find all elements with a particular class and then apply the lax attributes to them, e.g.
```
const els = document.querySelectorAll(".myClassName")

[...els].forEach((el) => {
  el.setAttribute("data-lax-preset", "myPresetName")
  // add more required attributes here
});

lax.updateElements() // this will make lax search the document again for elements to animate
```

Hope this helps :)

**Comment by PubliAlex** [comment]
Thank you very much, it will help for sure !
