### ISSUE TITLE
Feature Request: Animation Easings?

### ISSUE THREAD

**Issue by chrisribal** [alexfoxy/laxxx#59]
First of all, this is by far the best scroll effects library out there! I was looking for a lightweight alternative to the ScrollMagic + GreenSock stack and this is finally something really useful! Great job!

I was just wondering if there are any plans to add support for easings? Im using lax.js to add some decent scroll effects to our website. As some of the animations stop right inside the viewport, it would be nice if we could add some easing effects to have them slow down before the animation ends.

**Comment by alexfoxy** [comment]
Heya! Glad you like the library :)

I did start development on momentum/easings this but didn't find a clean way to implement it. Perhaps I should have another look!

**Comment by chrisribal** [comment]
@alexfoxy Yes we're still using it on the project. Unfortunately, as the project is still under active development, i cannot post a public link. As soon as the project is published, i will come back and post the link here.

**Comment by drozumek** [comment]
You can achieve momentum via CSS, add this property to the animated element selector:
transition: transform 2s cubic-bezier(.2,.89,.44,1);

**Comment by alexfoxy** [comment]
> You can achieve momentum via CSS, add this property to the animated element selector:
> transition: transform 2s cubic-bezier(.2,.89,.44,1);

interesting, do you have an example ?

**Comment by drozumek** [comment]
Sure Alex, here you go
https://codepen.io/drozumek/pen/qBBKxGg

I used cubic bezier function, which decelerated smoothly at the end of transformation. You can achieve any effect this way, for example smooth acceleration at the beginning and at the end (just uncomment second transition and comment first one in my example).

**Comment by alexfoxy** [comment]
@drozumek very nice. I'll have a think how to incorporate this into the library as an option. Of course it can be achieved with just CSS. Thanks!

**Comment by Underclassity** [comment]
@alexfoxy I add easing support as params in this PR [https://github.com/alexfoxy/laxxx/pull/70](https://github.com/alexfoxy/laxxx/pull/70)

**Comment by alexfoxy** [comment]
@Underclassity thanks, I need to check it out.
@chrisribal do you want to take a look and see if PR #70 fits your needs?

**Comment by chrisribal** [comment]
@Underclassity thanks for the PR! Looks very promising!
@alexfoxy I justed checked it out and seems to be a really cool solution! I think this way fits all needs of applying easing.

**Comment by alexfoxy** [comment]
@Underclassity @chrisribal sorry for being slow on this one. Have either of you noticed any performance issues with easing?

**Comment by Underclassity** [comment]
@alexfoxy
I did not notice any performance issues. There is a moment with rendering floating-point values, but this needs to be solved separately. In the case of a small difference between the start and end values, the library generates numbers with a large floating point: for example, `transform:translateX(9.25e-07px);`.

**Comment by alexfoxy** [comment]
@Underclassity @chrisribal @drozumek closing this issue as I have worked easings into the new 2.0 version.

Check out the alpha here: https://github.com/alexfoxy/laxxx/tree/version-2
