### ISSUE TITLE
Not working with Gridsome

### ISSUE THREAD

**Issue by sergeyfilimonov** [alexfoxy/laxxx#6]
Trying to use it with Gridsome by adding this to `main.js`

```js
import lax from 'lax.js'
export default function (Vue, {router, head, isClient}) {
  Vue.use(lax)
}
```

But it's not working :/

**Comment by alexfoxy** [comment]
Can you post an example somewhere?

**Comment by sergeyfilimonov** [comment]
@alexfoxy https://github.com/sergeyfilimonov/sergeyfilimonov.com

See these files:
https://github.com/sergeyfilimonov/sergeyfilimonov.com/blob/master/src/main.js
https://github.com/sergeyfilimonov/sergeyfilimonov.com/blob/master/src/components/sections/Intro.vue

**Comment by alexfoxy** [comment]
I can't see where you are setting up lax and binding the window scroll event. e.g.
```
        lax.setup({ /* opts */ }) // init
	  
	document.addEventListener('scroll', function(e) {
	  lax.update(window.scrollY) // update every scroll
	}, false)

	lax.update(window.scrollY) // set initial positions
```
I think the setup might be slightly different for vue.js, see: 
https://stackoverflow.com/questions/45822150/how-to-listen-to-the-window-scroll-event-in-a-vuejs-component

**Comment by alexfoxy** [comment]
I've just added a new function that you might want to use when you add elements to the dom -`lax.populateElements` 

I updated the readme to: https://github.com/alexfoxy/laxxx#dealing-with-dom-changes

**Comment by alexfoxy** [comment]
@sergeyfilimonov hey - I have created a working example using vue.js here: https://codepen.io/alexfoxy/pen/ZPRZBq

Hopefully it'll help you out. Make sure you get the v1.0.5 release.
