### ISSUE TITLE
Using lax.js with Nuxt.js

### ISSUE THREAD

**Issue by alexverdaguer** [alexfoxy/laxxx#63]
When trying to use lax as the vue example got this error: "document is not defined" is there a workaround for using lax.js with SSR as a plugin or something ?

Using nuxt as "SPA" works properly.

**Comment by alexfoxy** [comment]
Heya - do you have a codepen for me to look at?

**Comment by alexfoxy** [comment]
@alexverdaguer Hey do you have an example?

**Comment by MarvinRudolph** [comment]
@alexverdaguer You need to check `process.client` and `require` it then. Or in `mounted` hook.
