### ISSUE TITLE
`vw` calculation includes scrollbar width

### ISSUE THREAD

**Issue by ryansalerno** [alexfoxy/laxxx#68]
Using `window.innerWidth` as your basis for `vw` makes sense, but this includes the scrollbar width, which can throw off centering calculations.

To pull an element to center, it may make sense to do something like translating it to `(vw*0.5-elw*0.5)` which won't be exactly centered to any other centered content on the page that doesn't include scrollbar width.

Replacing `window.innerWidth` with `document.body.clientWidth`here: https://github.com/alexfoxy/laxxx/blob/master/src/lax.js#L256 takes care of that.

It may also be useful to replace it for your breakpoint calculation: https://github.com/alexfoxy/laxxx/blob/master/src/lax.js#L328 but I haven't used that and so didn't test....

(Also, I was stuck for a while expecting `vw` to work like it does in CSS, so my `50vw` was netting me crazy large numbers when I needed `(vw*0.5)`. The information is in the readme, but it might be worth a line calling out that it's not used the same?)

**Comment by alexfoxy** [comment]
Heya, that makes sense.

Following the CSS specifications for vw would have been a good idea.. bit late now though. I will add something to the readme however :)

**Comment by alexfoxy** [comment]
Hey @ryansalerno !

Just a heads up that I have worked this fix into the new 2.0 version. Check out the alpha here: https://github.com/alexfoxy/laxxx/tree/version-2
