### ISSUE TITLE
provide a variable for the entire page content height?

### ISSUE THREAD

**Issue by silky** [alexfoxy/laxxx#7]
this library is neat, i'm keen to have a go of it :)

however, i'm wondering if instead of just the viewport we could have a variable that is the computed height of the entire content? so we can have something at comes into focus as you scroll to the end of the content?

**Comment by silky** [comment]
i.e. the scrollHeight? - https://stackoverflow.com/a/44077777

**Comment by alexfoxy** [comment]
You can just use vanilla JS using ( )  e.g. 
```
<div data-lax-opacity="0 1, (document.body.scrollHeight - window.innerHeight) 0"></div>
```
In that example the div will start at opacity 1 and slowly fade until you have scrolled all the way to the bottom.
