### ISSUE TITLE
add/remove class on scroll?

### ISSUE THREAD

**Issue by sharanda** [alexfoxy/laxxx#72]
Hi, thanks for the plugin. Great work!

Is there any way to trigger class add/remove on an element with it?

**Comment by Underclassity** [comment]
It might be added later with pr [(https://github.com/alexfoxy/laxxx/pull/55](https://github.com/alexfoxy/laxxx/pull/55)

**Comment by sharanda** [comment]
@Underclassity thanks, that helped.

**Comment by ukathemes** [comment]
Join. It would be great to have this feature in version 2. Now you have to use a different script to do this. As a result, two scripts monitor the scroll position, which is not very good for performance.
