### ISSUE TITLE
Is it possible to add laxxx effects to elements inside of a fixed div with 'overflow: scroll'?

### ISSUE THREAD

**Issue by rchrdnsh** [alexfoxy/laxxx#73]
I see that this uses the windows scroll position, but would it be possible to add laxxx effects to the elements inside of a div that is fixed, but has `overflow-y: scroll`?

also curious how that might be implemented using the react hooks version as well :-)

I might have missed it in the docs, if so, my apologies :-)

**Comment by alexfoxy** [comment]
Yes this is possible. Check my answer to: #66 https://github.com/alexfoxy/laxxx/issues/66

**Comment by rchrdnsh** [comment]
yup, totally did not see that one, thank you :-)

**Comment by rchrdnsh** [comment]
sweet, it worked!

I just made my own hook, ala `useLax`, like so, directly in the component I'm parallaxing in:

```jsx
function useLax() {
  const requestRef = useRef();

  useEffect(() => {
    lax.setup() // initialization
    const element = document.querySelector('#scroller') // Find your scrollable element

    const updateLax = () => {
      lax.update(element.scrollTop) // pass in the elements scrolled position
      requestRef.current = window.requestAnimationFrame(updateLax);
    };

    requestRef.current = window.requestAnimationFrame(updateLax);

    return () => {
      if (requestRef.current) {
        window.cancelAnimationFrame(requestRef.current);
      }
    };
  }, []);
}
```

Thank you for this library! XD
