### ISSUE TITLE
Turn Animation Off

### ISSUE THREAD

**Issue by ekinch** [alexfoxy/laxxx#76]
Is there a way to turn the animation off?? I'm trying to keep a website accessible and I am adding a toggle to disable animations do you have anything native to the library that will disable / stop the animations??

**Comment by Underclassity** [comment]
@ekinch 
You can remove animated element from with `removeElement` method or remove all animation elements: `lax.elements.forEach(lax.removeElement)`

**Comment by alexfoxy** [comment]
In your updateLax function add a variable "lowPerformanceMode" that when true returns in the function.
