### ISSUE TITLE
Use of eval() is strongly discouraged

### ISSUE THREAD

**Issue by GitGangGuy** [alexfoxy/laxxx#77]
When spinning up a webapp with rollup and importing `lax.js` (in my case: I'm building a [sapper](http://sapper.svelte.dev) app), it complains about laxxx using the eval statement, which supposedly is a security risk and may cause issues with minification. It's only a mild warning, but I'd be happy if you guys could switch out that eval with something else sometime :wink: Thanks.

**Comment by alexfoxy** [comment]
Nice, I've been meaning to check out svelte - how is it?

Regarding eval, I was conscious of using it though I wanted to allow users to supply custom functions as strings to lax. I'm not sure if there's a way around this but I can take a look in the new year.

**Comment by GitGangGuy** [comment]
Alright, that sounds great!
Regarding svelte: I started using js frameworks a few months ago with VueJS, then Vue-CLI and then NuxtJS (before that I was mainly using php frameworks like laravel and jQuery on the client side 😞 ). I then found out about svelte and by now, I only work with sapper (the framework version of svelte) in my free time. It's so much easier to integrate compiler plugins (since all svelte files are already being compiled), so adding postcss plugins, preprocessor support and more is a breeze. It goes a step further than Vue in terms of ease of use and integrated capabilities (such as being able to modify the head directly from any svelte page, without any extra plugins) and unlike other frameworks like Nuxt, it doesn't try to hide the 'internals' behind the framework itself. It's really easy to add middleware, modify the server/client scripts and so on. Although I'd recommend sapper over any other framework for almost every situation, at the end of the day, it boils down to personal preference.

**Comment by alexfoxy** [comment]
@GitGangGuy not sure how to resolve the use of eval() if lax continues to support custom functions. Did you manage to find a work around?

**Comment by GitGangGuy** [comment]
Nope :) Anyway, if you insist on using custom functions the way they are currently implemented (which I can fully understand), I can go ahead and close the issue.

**Comment by alexfoxy** [comment]
@GitGangGuy I have recently discovered that you can use `Function(...)` to enable custom functions. I've worked this into the new 2.0 version I have been working on. Check out the alpha here: https://github.com/alexfoxy/laxxx/tree/version-2
