### ISSUE TITLE
Library bugged on firefox 

### ISSUE THREAD

**Issue by jojobagings78** [alexfoxy/laxxx#78]
I am guessing this library has been made with only chrome in mind since it lags on nearly every other browser apart from chrome ?

**Comment by alexfoxy** [comment]
How many browsers have you tried it in...? It's pretty simple at it's core so I don't see why it wouldn't perform well in other browsers, but I haven't tried it in Firefox.

**Comment by WhereCanI** [comment]
I have only seen it lag in Chrome on android and in Safari on iPad. On desktop it works great for me no matter which browser I use. 🙂

**Comment by alexfoxy** [comment]
Closing due to lack of information.

**Comment by jojobagings78** [comment]
It lags on firefox a lot, IE and mobile browsers.

**Comment by alexfoxy** [comment]
@jojobagings78 do you have an example?

The demo (https://alexfox.dev/laxxx/) is silky smooth on my iPhone.

Perhaps you’re doing something wrong.

**Comment by WhereCanI** [comment]
I think you might be right about that. I have a scroll effect on my website sliding the headlines up faster than the content plus bringing the opacity down. At the same time I at moving my background image slowly depending on how much you scroll. So it might be because I am stretching the browser and not something with the module.

**Comment by alexfoxy** [comment]
If you can share the code I can take a look?

**Comment by jojobagings78** [comment]
I have fixed the issue however I cam across another issue now. On initial page load the offset of when the animation triggers is wrong. If I change page and go back with a route on react it then is correct.

**Comment by alexfoxy** [comment]
Hey, it’s a little bit hard to help without seeing the code. Can you make a
code pen or something with the issue for me to take a look at?

**Comment by jojobagings78** [comment]
I am using SSR and this is what is used.

```
import lax from 'lax.js';

componentDidMount(){
  lax.setup()
  const update = () => {
    lax.update(window.scrollY)
    window.requestAnimationFrame(update)
  }
  window.requestAnimationFrame(update)
}

 <div id="animation_parralax">
  <div className="lax" data-lax-translate-y="(vh) 0, (-elh) 200" data-lax-opacity="offset=100" data-lax-anchor="#animation_parralax">IMAGE HERE</div>
  <div className="lax" data-lax-translate-y="(vh) 0, (-elh) -200" data-lax-opacity="offset=100" data-lax-anchor="#animation_parralax">IMAGE HERE</div>
 </div>
```

**Comment by jojobagings78** [comment]
@alexfoxy I believe the above is correct

**Comment by jojobagings78** [comment]
I was able to fix the issue however on using this library on a ssr website it seems to require you to resize page for the parralax to work correctly any idea around this ?
