### ISSUE TITLE
Styles - positioning absolute and from bottom

### ISSUE THREAD

**Issue by duszczak** [alexfoxy/laxxx#80]
Hi.
Today i encoutered problem. I have image:
`<img src="/images/top-building.png" class="bg-top-building lax" data-lax-translate-y="0 -300, (vh) 0" data-lax-anchor="self" />`
and styles for it:
`.bg-top-building{
			position: absolute;
			z-index: 2;
			width: 100%;
			bottom:0;
			left:0;
		}`
I've noticed that for some reason laxxx isn't calculating translation. All it does is set start values and while scrolling nothing changes. If i change `bottom:0;` to for example `top:0;` all acts as it should.

Any suggestion what can be the cause and fix for this behavior?

**Comment by duszczak** [comment]
i did some new discovery. It seems that `translate` isn't changing if elemnt is somewhat on negative value from top. So if i set ie. `top:-100px;` it behaves simmilar as when it is set to `bottom:0;`. In other words `translate` isn't applied when element is sticking up above parent.

**Comment by alexfoxy** [comment]
Hi, did you ever find a solution? I am closing for now. If you could create a codepen with the issue that would be great.
