### ISSUE TITLE
Add 'data-lax-translate-3d' attribute key / ability to add custom attribute keys

### ISSUE THREAD

**Issue by joesawa** [alexfoxy/laxxx#81]
I am currently using an old version of laxxx because I needed to add a `data-lax-translate-3d` attribute key to `transformFns`.

`data-lax-translate-3d` is necessary to avoid conflicting css I have in regards to the inline styles generated by `translate-x` and `translate-y`. Using the `transform: translate3d();` css property avoids these conflicts. It is also purportedly more performance efficient.

I have currently added an implementation as follows:

```
const transformFns = {
   ...
   "data-lax-translate-3d": (style, v) => { style.transform += ` translate3d(0px,${v}px,0px)` },
    ...
};
````

I'm sure this can be expounded upon. Thanks for reading.

**Comment by alexfoxy** [comment]
hey @joesawa 

I've been working on a 2.0 update which allows you to specify a custom css animation. Check out the alpha here: https://github.com/alexfoxy/laxxx/tree/version-2
