### ISSUE TITLE
Calculation bug on first element on the page

### ISSUE THREAD

**Issue by janein** [alexfoxy/laxxx#83]
Hi,

when an element is placed first on the page (exactly on top), the translate-y always moves into positive numbers, even if defined as a negative.

You can see the behaviour on this example:
https://codepen.io/janein/pen/oNXZEbG

All elements have the same animaiton. They come in from `+250px` and should leave to `-250px`. It works fine on all elements except the first one.
If I move my first elements by `1px` (i.e. apply a "`margin-top: 1px`") is works.
But I can't live with this workaround in my case.

Any idea why this happens?

Thanks, 
janein

**Comment by alexfoxy** [comment]
It does seem kind of strange. Did you ever find a fix?

**Comment by janein** [comment]
Sadly not.
Wherever possible I just moved the element down by 1px.

**Comment by alexfoxy** [comment]
@janein Just to let you know I have been working on a new lax 2.0 version which I thought you might be interested in trying out. Check out the alpha here: https://github.com/alexfoxy/laxxx/tree/version-2
