### ISSUE TITLE
CSS filters not rendered

### ISSUE THREAD

**Issue by LeonSkrilec** [alexfoxy/laxxx#88]
I want to transition an element from 50% grayscale to 0% grayscale like this:
`data-lax-grayscale="vh 50%, 0 0%"`

Code is working and laxxx is animating the grayscale value of the elements filter. 
The thing is, that filters get applied twice, like this: `filter: grayscale(50%) grayscale(0%)` and laxxx is animating the second value, which is not rendered by the browser and therefore it is not visible on the screen because browser obeys first value. So element stays at 50% grayscale all the time.

This is on Mac - Chrome. 

Is this an issue or should I check my code?

Thanks for help!
Leon

**Comment by alexfoxy** [comment]
Sounds like it might be a bug! Could you create a code pen that I could take a look at?

**Comment by alexfoxy** [comment]
Let me know if you managed to reproduce this! Closing for now.
