### ISSUE TITLE
Doesn't work with object already translated

### ISSUE THREAD

**Issue by MaxZiebell** [alexfoxy/laxxx#9]
I think this my just be a overhead on these elements and this library shouldn't care about them… on the other hand having elements already defining translation etc. respected would maybe broaden use cases.

**Comment by alexfoxy** [comment]
Yes this is true. Are you expecting to merge values or combine keys?

**Comment by alexfoxy** [comment]
@MaxZiebell did you have any further thoughts on this?

**Comment by MaxZiebell** [comment]
Lax could take the given offsets on init and add them to it's own animation. Not sure if that is viable without bloating.

**Comment by alexfoxy** [comment]
Yea makes sense, it would have to take the original css value e.g. "translateX(12pt) scale(1)" and then mix in its own values somehow. Do you have a specific example?

**Comment by MaxZiebell** [comment]
Yes but one I can't share at this point but it boils down to any element using positions with tranlastion or other CSS values and it would be good practice to respect any preexisting values. Also has the nice side effect that you can do layouts and lax presets would work relative to the initial conditions. Like if you had a text rotated -90degrees … it would start a turn from there and not reset it to the lax setting.

**Comment by alexfoxy** [comment]
It seems a bit weird to be using translate to position stuff, it should be used for animations. I hear your point tho and I've had a look but need to change a bit of implementation to get it to work.

**Comment by MaxZiebell** [comment]
In theory your right but the world is a messy place with many CSS hack like this one https://css-tricks.com/centering-percentage-widthheight-elements/  … This is just one example using translation to hack its way to a specific goal.

**Comment by alexfoxy** [comment]
Yes, I'll have to see how I can work it out. You'd have to convert
something like that hack to real pixel values.

**Comment by MaxZiebell** [comment]
Don't beat yourself up over it. Unless your trying to build an all purpose tool we can live with it. One just needs to remember it when using lax. For my purpose I already worked around it. Consider size and complexly vs simplicty and lightweight of this against each other. Iax is also cool because it's small and fast. When nobody else runs against this it might just be fine the way it is!

**Comment by alexfoxy** [comment]
Of course. Just want the library to feel like it just works.. ;D

**Comment by alexfoxy** [comment]
I think I have worked out a way. Will be in next update.

**Comment by alexfoxy** [comment]
Fixed in 1.2.0 release
