### ISSUE TITLE
Using breakpoints with presets

### ISSUE THREAD

**Issue by coreybyrum7** [alexfoxy/laxxx#90]
@alexfoxy @afanjul 

Is there a plan to allow for breakpoints with presets? It would be very useful when creating custom presets for code reusability.

**Comment by PubliAlex** [comment]
Did you find some infos ? The only breakpoints support I see on the doc is when you define animation programatically. I remember the V1 supported breakpoints with presets, I'm surprised to not see this in V2

**Comment by PubliAlex** [comment]
Did you find some infos ? The only breakpoints support I see on the doc is when you define animation programatically. I remember the V1 supported breakpoints with presets, I'm surprised to not see this in V2
